# Generated by Django 5.1.1 on 2024-11-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
